---
_extends: .github

repository:
  name: hs-msgpack-binary
  description: Haskell implementation of MessagePack / msgpack.org
  homepage: http://msgpack.org/
  topics: msgpack, haskell
  has_issues: true

branches:
  - name: "master"
    protection:
      required_status_checks:
        contexts:
          - cirrus-ci
          - Codacy Static Code Analysis
          - code-review/reviewable
